spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/enumtest
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false